### ISSUE TITLE
Update LICENSE to Bauddhik-Geeks

### ISSUE THREAD

**Issue by harikanani** [Bauddhik-Geeks/Garuda#2]
- Change License Owner from `EFFLUX` to `Bauddhik-Geeks`

**Comment by adityamangal1** [comment]
@EFFLUX110 You can do this by yourself too

**Comment by harikanani** [comment]
@adityamangal1 this is for very beginners to start their open source contribution

**Comment by Mrinank-Bhowmick** [comment]
> @EFFLUX110 You can do this by yourself too

@harikanani told me to keep it for others to contribute.

**Comment by Mrinank-Bhowmick** [comment]
@all-contributors please add @Rajkumar-stackcoder  for code contribution

**Comment by Mrinank-Bhowmick** [comment]
@all-contributors please add @EFFLUX110 for code contribution
